spring:
  application:
    name: pagila-api
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
springdoc:
  enabled-spring-security: true
  cache:
    disabled: true
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-docs.html
    operationsSorter: method
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when-authorized
    info:
      show-details: when-authorized
server:
  port: ${PORT:8080}
  servlet:
    context-path: /pagila
